### ISSUE TITLE
aiogram\dispatcher\dispatcher.py

### ISSUE THREAD

**Issue by ivan-bryliant** [darksidecat/aiogram-multibot-example#4] opened 2022-07-07 13:42 UTC
error:   File "C:\Users\AppData\Local\Programs\Python\Python310\lib\site-packages\aiogram\dispatcher\dispatcher.py", line 52, in __init__
    super(Dispatcher, self).__init__(**kwargs)
TypeError: Router.__init__() got an unexpected keyword argument 'isolate_events'

aiogram 3.0.0b
python 3.10.3

**Comment by darksidecat** [comment] 2022-07-07 22:20
Fixed in https://github.com/darksidecat/aiogram-multibot-example/commit/cb21b0bcfe6e8ce6649b14724aaf8ca1ab08591a

Please let me know if the problem is gone

**Comment by ivan-bryliant** [comment] 2022-07-08 14:15
yes it works thank you very much!🙌

**Closed as completed** 2022-07-08 16:57 UTC
